'use strict';

// Your code goes here.
//
// During the "build" step, two versions of your file will be generated by `grunt rigger` and the scripts in the /build folder:
// 1) AMD version
// 2) IIFE version

function WebStorage(scope){
	if (typeof scope == 'undefined') {
		scope = 'localStorage';
	}

	if (scope != 'localStorage' && scope != 'sessionStorage') {
		throw new Error('Unsupported scope given in webStorage');
	}

	if (!window.localStorage || !window.sessionStorage) {
		throw new Error('Unsupported Browser');
	}

	if (scope == 'localStorage') {
		this.scope = window.localStorage;
	}

	if (scope == 'sessionStorage') {
		this.scope = window.sessionStorage;
	}
}

WebStorage.prototype = {
	get: function(){
	
	}
	,set: function(){

	}
	,rm: function(){
	
	}
	,flush: function(){

	}
	,getAll: function(){

	}

};



